/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteBankingTransactionArgs } from "./DeleteBankingTransactionArgs";
import { BankingTransactionCountArgs } from "./BankingTransactionCountArgs";
import { BankingTransactionFindManyArgs } from "./BankingTransactionFindManyArgs";
import { BankingTransactionFindUniqueArgs } from "./BankingTransactionFindUniqueArgs";
import { BankingTransaction } from "./BankingTransaction";
import { BankingTransactionService } from "../bankingTransaction.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => BankingTransaction)
export class BankingTransactionResolverBase {
  constructor(
    protected readonly service: BankingTransactionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "BankingTransaction",
    action: "read",
    possession: "any",
  })
  async _bankingTransactionsMeta(
    @graphql.Args() args: BankingTransactionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [BankingTransaction])
  @nestAccessControl.UseRoles({
    resource: "BankingTransaction",
    action: "read",
    possession: "any",
  })
  async bankingTransactions(
    @graphql.Args() args: BankingTransactionFindManyArgs
  ): Promise<BankingTransaction[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => BankingTransaction, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "BankingTransaction",
    action: "read",
    possession: "own",
  })
  async bankingTransaction(
    @graphql.Args() args: BankingTransactionFindUniqueArgs
  ): Promise<BankingTransaction | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => BankingTransaction)
  @nestAccessControl.UseRoles({
    resource: "BankingTransaction",
    action: "delete",
    possession: "any",
  })
  async deleteBankingTransaction(
    @graphql.Args() args: DeleteBankingTransactionArgs
  ): Promise<BankingTransaction | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
